// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).
using System;
using System.Runtime.Serialization;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Collections;
using System.ComponentModel.DataAnnotations;
using System.Linq.Expressions;
using zAppDev.DotNet.Framework.Linq;
using zAppDev.DotNet.Framework.Data.Domain;
using zAppDev.DotNet.Framework.Workflow;
using zAppDev.DotNet.Framework.Identity.Model;

namespace DemonstratorApp.BO
{
    /// <summary>
    /// The InvoiceProduct class
    ///
    /// </summary>
    [Serializable]
    [DataContract]
    public class InvoiceProduct : IDomainModelClass
    {
        #region InvoiceProduct's Fields

        protected Guid _transientId= Guid.NewGuid();
        public virtual Guid TransientId
        {
            get
            {
                return _transientId;
            }
            set
            {
                _transientId = value;
            }
        }
        [DataMember(Name="Id")]
        protected int? id = 0;
        [DataMember(Name="Code")]
        protected string code;
        [DataMember(Name="Quantity")]
        protected decimal? quantity;
        [DataMember(Name="Description")]
        protected string description;
        [DataMember(Name="UnitValue")]
        protected string unitValue;
        [DataMember(Name="MeasurementUnit")]
        protected string measurementUnit;
        [DataMember(Name="Price")]
        protected decimal? price;
        [DataMember(Name="LineTotalPrice")]
        protected decimal? lineTotalPrice;
        [DataMember(Name="VersionTimestamp")]
        protected byte[] versionTimestamp;

        #endregion
        #region InvoiceProduct's Properties
/// <summary>
/// The Id property
///
/// </summary>
///
        [Key]
        public virtual int? Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }
/// <summary>
/// The Code property
///
/// </summary>
///
        public virtual string Code
        {
            get
            {
                return code;
            }
            set
            {
                code = value;
            }
        }
/// <summary>
/// The Quantity property
///
/// </summary>
///
        public virtual decimal? Quantity
        {
            get
            {
                return quantity;
            }
            set
            {
                quantity = value;
            }
        }
/// <summary>
/// The Description property
///
/// </summary>
///
        public virtual string Description
        {
            get
            {
                return description;
            }
            set
            {
                description = value;
            }
        }
/// <summary>
/// The UnitValue property
///
/// </summary>
///
        public virtual string UnitValue
        {
            get
            {
                return unitValue;
            }
            set
            {
                unitValue = value;
            }
        }
/// <summary>
/// The MeasurementUnit property
///
/// </summary>
///
        public virtual string MeasurementUnit
        {
            get
            {
                return measurementUnit;
            }
            set
            {
                measurementUnit = value;
            }
        }
/// <summary>
/// The Price property
///
/// </summary>
///
        public virtual decimal? Price
        {
            get
            {
                return price;
            }
            set
            {
                price = value;
            }
        }
/// <summary>
/// The LineTotalPrice property
///
/// </summary>
///
        public virtual decimal? LineTotalPrice
        {
            get
            {
                return lineTotalPrice;
            }
            set
            {
                lineTotalPrice = value;
            }
        }
/// <summary>
/// The VersionTimestamp property
///Provides concurrency control for the class
/// </summary>
///
        public virtual byte[] VersionTimestamp
        {
            get
            {
                return versionTimestamp;
            }
            set
            {
                versionTimestamp = value;
            }
        }
        #endregion
        #region InvoiceProduct's Participant Properties
        [DataMember(Name="Invoice")]
        protected Invoice invoice;
        public virtual Invoice Invoice
        {
            get
            {
                return invoice;
            }
            set
            {
                if(Equals(invoice, value)) return;
                var __oldValue = invoice;
                invoice?.InternalRemoveInvoiceProducts(this);
                invoice = value;
                if (value != null)
                {
                    invoice.InternalAddInvoiceProducts(this);
                }
            }
        }
        [DataMember(Name="SupplierProduct")]
        protected SupplierProduct supplierProduct;
        public virtual SupplierProduct SupplierProduct
        {
            get
            {
                return supplierProduct;
            }
            set
            {
                if(Equals(supplierProduct, value)) return;
                var __oldValue = supplierProduct;
                if (value != null)
                {
                    supplierProduct = value;
                }
                else
                {
                    if (supplierProduct != null)
                    {
                        supplierProduct = null;
                    }
                }
            }
        }
        #endregion
        #region Constructors
/// <summary>
/// Public constructors of the InvoiceProduct class
/// </summary>
/// <returns>New InvoiceProduct object</returns>
/// <remarks></remarks>
        public InvoiceProduct() {}
        #endregion
        #region Methods

        public virtual List<string> _Validate(bool throwException = true)
        {
            var __errors = new List<string>();
            if (Id == null)
            {
                __errors.Add("Property 'Id' is required.");
            }
            if (Code != null && Code.Length > 100)
            {
                __errors.Add("Length of property 'Code' cannot be greater than 100.");
            }
            if (Description != null && Description.Length > 100)
            {
                __errors.Add("Length of property 'Description' cannot be greater than 100.");
            }
            if (UnitValue != null && UnitValue.Length > 100)
            {
                __errors.Add("Length of property 'UnitValue' cannot be greater than 100.");
            }
            if (MeasurementUnit != null && MeasurementUnit.Length > 100)
            {
                __errors.Add("Length of property 'MeasurementUnit' cannot be greater than 100.");
            }
            if (throwException && __errors.Any())
            {
                throw new zAppDev.DotNet.Framework.Exceptions.BusinessException("An instance of TypeClass 'InvoiceProduct' has validation errors:\r\n\r\n" + string.Join("\r\n", __errors));
            }
            return __errors;
        }

        public virtual int _GetUniqueIdentifier()
        {
            var hashCode = 399326290;
            hashCode = hashCode * -1521134295 + (Id?.GetHashCode() ?? 0);
            hashCode = hashCode * -1521134295 + (Code?.GetHashCode() ?? 0);
            hashCode = hashCode * -1521134295 + (Quantity?.GetHashCode() ?? 0);
            hashCode = hashCode * -1521134295 + (Description?.GetHashCode() ?? 0);
            hashCode = hashCode * -1521134295 + (UnitValue?.GetHashCode() ?? 0);
            hashCode = hashCode * -1521134295 + (MeasurementUnit?.GetHashCode() ?? 0);
            hashCode = hashCode * -1521134295 + (Price?.GetHashCode() ?? 0);
            hashCode = hashCode * -1521134295 + (LineTotalPrice?.GetHashCode() ?? 0);
            return hashCode;
        }






/// <summary>
/// Copies the current object to a new instance
/// </summary>
/// <param name="deep">Copy members that refer to objects external to this class (not dependent)</param>
/// <param name="copiedObjects">Objects that should be reused</param>
/// <param name="asNew">Copy the current object as a new one, ready to be persisted, along all its members.</param>
/// <param name="reuseNestedObjects">If asNew is true, this flag if set, forces the reuse of all external objects.</param>
/// <param name="copy">Optional - An existing [InvoiceProduct] instance to use as the destination.</param>
/// <returns>A copy of the object</returns>
        public virtual InvoiceProduct Copy(bool deep=false, Hashtable copiedObjects=null, bool asNew=false, bool reuseNestedObjects = false, InvoiceProduct copy = null)
        {
            if(copiedObjects == null)
            {
                copiedObjects = new Hashtable();
            }
            if (copy == null && copiedObjects.Contains(this))
                return (InvoiceProduct)copiedObjects[this];
            copy = copy ?? new InvoiceProduct();
            if (!asNew)
            {
                copy.TransientId = this.TransientId;
                copy.Id = this.Id;
            }
            copy.Code = this.Code;
            copy.Quantity = this.Quantity;
            copy.Description = this.Description;
            copy.UnitValue = this.UnitValue;
            copy.MeasurementUnit = this.MeasurementUnit;
            copy.Price = this.Price;
            copy.LineTotalPrice = this.LineTotalPrice;
            if (!copiedObjects.Contains(this))
            {
                copiedObjects.Add(this, copy);
            }
            if(deep && this.invoice != null)
            {
                if (!copiedObjects.Contains(this.invoice))
                {
                    if (asNew && reuseNestedObjects)
                        copy.Invoice = this.Invoice;
                    else if (asNew)
                        copy.Invoice = this.Invoice.Copy(deep, copiedObjects, true);
                    else
                        copy.invoice = this.invoice.Copy(deep, copiedObjects, false);
                }
                else
                {
                    if (asNew)
                        copy.Invoice = (Invoice)copiedObjects[this.Invoice];
                    else
                        copy.invoice = (Invoice)copiedObjects[this.Invoice];
                }
            }
            if(deep && this.supplierProduct != null)
            {
                if (!copiedObjects.Contains(this.supplierProduct))
                {
                    if (asNew && reuseNestedObjects)
                        copy.SupplierProduct = this.SupplierProduct;
                    else if (asNew)
                        copy.SupplierProduct = this.SupplierProduct.Copy(deep, copiedObjects, true);
                    else
                        copy.supplierProduct = this.supplierProduct.Copy(deep, copiedObjects, false);
                }
                else
                {
                    if (asNew)
                        copy.SupplierProduct = (SupplierProduct)copiedObjects[this.SupplierProduct];
                    else
                        copy.supplierProduct = (SupplierProduct)copiedObjects[this.SupplierProduct];
                }
            }
            return copy;
        }

        public override bool Equals(object obj)
        {
            var compareTo = obj as InvoiceProduct;
            if (ReferenceEquals(this, compareTo))
            {
                return true;
            }
            if (compareTo == null || !this.GetType().Equals(compareTo.GetTypeUnproxied()))
            {
                return false;
            }
            if (this.HasSameNonDefaultIdAs(compareTo))
            {
                return true;
            }
            // Since the Ids aren't the same, both of them must be transient to
            // compare domain signatures; because if one is transient and the
            // other is a persisted entity, then they cannot be the same object.
            return this.IsTransient() && compareTo.IsTransient() && (base.Equals(compareTo) || this.TransientId.Equals(compareTo.TransientId));
        }

// Maintain equality operator semantics for entities.
        public static bool operator ==(InvoiceProduct x, InvoiceProduct y)
        {
            // By default, == and Equals compares references. In order to
            // maintain these semantics with entities, we need to compare by
            // identity value. The Equals(x, y) override is used to guard
            // against null values; it then calls EntityEquals().
            return Equals(x, y);
        }

// Maintain inequality operator semantics for entities.
        public static bool operator !=(InvoiceProduct x, InvoiceProduct y)
        {
            return !(x == y);
        }

        private PropertyInfo __propertyKeyCache;
        public virtual PropertyInfo GetPrimaryKey()
        {
            if (__propertyKeyCache == null)
            {
                __propertyKeyCache = this.GetType().GetProperty("Id");
            }
            return __propertyKeyCache;
        }


/// <summary>
///     To help ensure hashcode uniqueness, a carefully selected random number multiplier
///     is used within the calculation.  Goodrich and Tamassia's Data Structures and
///     Algorithms in Java asserts that 31, 33, 37, 39 and 41 will produce the fewest number
///     of collissions.  See http://computinglife.wordpress.com/2008/11/20/why-do-hash-functions-use-prime-numbers/
///     for more information.
/// </summary>
        private const int HashMultiplier = 31;
        private int? cachedHashcode;

        public override int GetHashCode()
        {
            if (this.cachedHashcode.HasValue)
            {
                return this.cachedHashcode.Value;
            }
            if (this.IsTransient())
            {
                //this.cachedHashcode = base.GetHashCode();
                return this.TransientId.GetHashCode(); //don't cache because this won't stay transient forever
            }
            else
            {
                unchecked
                {
                    // It's possible for two objects to return the same hash code based on
                    // identically valued properties, even if they're of two different types,
                    // so we include the object's type in the hash calculation
                    var hashCode = this.GetType().GetHashCode();
                    this.cachedHashcode = (hashCode * HashMultiplier) ^ this.Id.GetHashCode();
                }
            }
            return this.cachedHashcode.Value;
        }

/// <summary>
///     Transient objects are not associated with an item already in storage.  For instance,
///     a Customer is transient if its Id is 0.  It's virtual to allow NHibernate-backed
///     objects to be lazily loaded.
/// </summary>
        public virtual bool IsTransient()
        {
            return this.Id == default(int) || this.Id.Equals(default(int));
        }

/// <summary>
///     When NHibernate proxies objects, it masks the type of the actual entity object.
///     This wrapper burrows into the proxied object to get its actual type.
///
///     Although this assumes NHibernate is being used, it doesn't require any NHibernate
///     related dependencies and has no bad side effects if NHibernate isn't being used.
///
///     Related discussion is at http://groups.google.com/group/sharp-architecture/browse_thread/thread/ddd05f9baede023a ...thanks Jay Oliver!
/// </summary>
        protected virtual System.Type GetTypeUnproxied()
        {
            return this.GetType();
        }

/// <summary>
///     Returns true if self and the provided entity have the same Id values
///     and the Ids are not of the default Id value
/// </summary>
        protected bool HasSameNonDefaultIdAs(InvoiceProduct compareTo)
        {
            return !this.IsTransient() && !compareTo.IsTransient() && this.Id.Equals(compareTo.Id);
        }

        #endregion


    }
}
