// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).
using System;
using System.Runtime.Serialization;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Collections;
using System.ComponentModel.DataAnnotations;
using System.Linq.Expressions;
using zAppDev.DotNet.Framework.Linq;
using zAppDev.DotNet.Framework.Data.Domain;
using zAppDev.DotNet.Framework.Workflow;
using zAppDev.DotNet.Framework.Identity.Model;

namespace DemonstratorApp.BO
{
    /// <summary>
    /// The TransactionStatus class
    ///
    /// </summary>
    [Serializable]
    [DataContract]
    public class TransactionStatus : IDomainModelClass
    {
        #region TransactionStatus's Fields

        protected Guid _transientId= Guid.NewGuid();
        public virtual Guid TransientId
        {
            get
            {
                return _transientId;
            }
            set
            {
                _transientId = value;
            }
        }
        [DataMember(Name="Id")]
        protected int? id = 0;
        [DataMember(Name="TransactionDateOccured")]
        protected DateTime? transactionDateOccured;
        [DataMember(Name="Status")]
        protected string status;
        [DataMember(Name="Shipped")]
        protected bool shipped;
        [DataMember(Name="Invoiced")]
        protected bool invoiced;
        [DataMember(Name="ShippedDateOccured")]
        protected DateTime? shippedDateOccured;
        [DataMember(Name="InvoicedDateOccured")]
        protected DateTime? invoicedDateOccured;
        [DataMember(Name="Cancelled")]
        protected bool cancelled;
        [DataMember(Name="InTransit")]
        protected bool inTransit;
        [DataMember(Name="Picked")]
        protected bool picked;
        [DataMember(Name="PaymentStatus")]
        protected bool paymentStatus;
        [DataMember(Name="InitialOrderDate")]
        protected DateTime? initialOrderDate;
        [DataMember(Name="FinalOrderDate")]
        protected DateTime? finalOrderDate;
        [DataMember(Name="Delivered")]
        protected bool delivered;
        [DataMember(Name="Ordered")]
        protected bool ordered;
        [DataMember(Name="VersionTimestamp")]
        protected byte[] versionTimestamp;

        #endregion
        #region TransactionStatus's Properties
/// <summary>
/// The Id property
///
/// </summary>
///
        [Key]
        public virtual int? Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }
/// <summary>
/// The TransactionDateOccured property
///
/// </summary>
///
        public virtual DateTime? TransactionDateOccured
        {
            get
            {
                return transactionDateOccured;
            }
            set
            {
                transactionDateOccured = value;
            }
        }
/// <summary>
/// The Status property
///
/// </summary>
///
        public virtual string Status
        {
            get
            {
                return status;
            }
            set
            {
                status = value;
            }
        }
/// <summary>
/// The Shipped property
///
/// </summary>
///
        public virtual bool Shipped
        {
            get
            {
                return shipped;
            }
            set
            {
                shipped = value;
            }
        }
/// <summary>
/// The Invoiced property
///
/// </summary>
///
        public virtual bool Invoiced
        {
            get
            {
                return invoiced;
            }
            set
            {
                invoiced = value;
            }
        }
/// <summary>
/// The ShippedDateOccured property
///
/// </summary>
///
        public virtual DateTime? ShippedDateOccured
        {
            get
            {
                return shippedDateOccured;
            }
            set
            {
                shippedDateOccured = value;
            }
        }
/// <summary>
/// The InvoicedDateOccured property
///
/// </summary>
///
        public virtual DateTime? InvoicedDateOccured
        {
            get
            {
                return invoicedDateOccured;
            }
            set
            {
                invoicedDateOccured = value;
            }
        }
/// <summary>
/// The Cancelled property
///
/// </summary>
///
        public virtual bool Cancelled
        {
            get
            {
                return cancelled;
            }
            set
            {
                cancelled = value;
            }
        }
/// <summary>
/// The InTransit property
///
/// </summary>
///
        public virtual bool InTransit
        {
            get
            {
                return inTransit;
            }
            set
            {
                inTransit = value;
            }
        }
/// <summary>
/// The Picked property
///
/// </summary>
///
        public virtual bool Picked
        {
            get
            {
                return picked;
            }
            set
            {
                picked = value;
            }
        }
/// <summary>
/// The PaymentStatus property
///
/// </summary>
///
        public virtual bool PaymentStatus
        {
            get
            {
                return paymentStatus;
            }
            set
            {
                paymentStatus = value;
            }
        }
/// <summary>
/// The InitialOrderDate property
///
/// </summary>
///
        public virtual DateTime? InitialOrderDate
        {
            get
            {
                return initialOrderDate;
            }
            set
            {
                initialOrderDate = value;
            }
        }
/// <summary>
/// The FinalOrderDate property
///
/// </summary>
///
        public virtual DateTime? FinalOrderDate
        {
            get
            {
                return finalOrderDate;
            }
            set
            {
                finalOrderDate = value;
            }
        }
/// <summary>
/// The Delivered property
///
/// </summary>
///
        public virtual bool Delivered
        {
            get
            {
                return delivered;
            }
            set
            {
                delivered = value;
            }
        }
/// <summary>
/// The Ordered property
///
/// </summary>
///
        public virtual bool Ordered
        {
            get
            {
                return ordered;
            }
            set
            {
                ordered = value;
            }
        }
/// <summary>
/// The VersionTimestamp property
///Provides concurrency control for the class
/// </summary>
///
        public virtual byte[] VersionTimestamp
        {
            get
            {
                return versionTimestamp;
            }
            set
            {
                versionTimestamp = value;
            }
        }
        #endregion
        #region Constructors
/// <summary>
/// Public constructors of the TransactionStatus class
/// </summary>
/// <returns>New TransactionStatus object</returns>
/// <remarks></remarks>
        public TransactionStatus() {}
        #endregion
        #region Methods

        public virtual List<string> _Validate(bool throwException = true)
        {
            var __errors = new List<string>();
            if (Id == null)
            {
                __errors.Add("Property 'Id' is required.");
            }
            if (Status != null && Status.Length > 100)
            {
                __errors.Add("Length of property 'Status' cannot be greater than 100.");
            }
            if (throwException && __errors.Any())
            {
                throw new zAppDev.DotNet.Framework.Exceptions.BusinessException("An instance of TypeClass 'TransactionStatus' has validation errors:\r\n\r\n" + string.Join("\r\n", __errors));
            }
            return __errors;
        }

        public virtual int _GetUniqueIdentifier()
        {
            var hashCode = 399326290;
            hashCode = hashCode * -1521134295 + (Id?.GetHashCode() ?? 0);
            hashCode = hashCode * -1521134295 + (TransactionDateOccured?.GetHashCode() ?? 0);
            hashCode = hashCode * -1521134295 + (Status?.GetHashCode() ?? 0);
            hashCode = hashCode * -1521134295 + (Shipped.GetHashCode() );
            hashCode = hashCode * -1521134295 + (Invoiced.GetHashCode() );
            hashCode = hashCode * -1521134295 + (ShippedDateOccured?.GetHashCode() ?? 0);
            hashCode = hashCode * -1521134295 + (InvoicedDateOccured?.GetHashCode() ?? 0);
            hashCode = hashCode * -1521134295 + (Cancelled.GetHashCode() );
            hashCode = hashCode * -1521134295 + (InTransit.GetHashCode() );
            hashCode = hashCode * -1521134295 + (Picked.GetHashCode() );
            hashCode = hashCode * -1521134295 + (PaymentStatus.GetHashCode() );
            hashCode = hashCode * -1521134295 + (InitialOrderDate?.GetHashCode() ?? 0);
            hashCode = hashCode * -1521134295 + (FinalOrderDate?.GetHashCode() ?? 0);
            hashCode = hashCode * -1521134295 + (Delivered.GetHashCode() );
            hashCode = hashCode * -1521134295 + (Ordered.GetHashCode() );
            return hashCode;
        }






/// <summary>
/// Copies the current object to a new instance
/// </summary>
/// <param name="deep">Copy members that refer to objects external to this class (not dependent)</param>
/// <param name="copiedObjects">Objects that should be reused</param>
/// <param name="asNew">Copy the current object as a new one, ready to be persisted, along all its members.</param>
/// <param name="reuseNestedObjects">If asNew is true, this flag if set, forces the reuse of all external objects.</param>
/// <param name="copy">Optional - An existing [TransactionStatus] instance to use as the destination.</param>
/// <returns>A copy of the object</returns>
        public virtual TransactionStatus Copy(bool deep=false, Hashtable copiedObjects=null, bool asNew=false, bool reuseNestedObjects = false, TransactionStatus copy = null)
        {
            if(copiedObjects == null)
            {
                copiedObjects = new Hashtable();
            }
            if (copy == null && copiedObjects.Contains(this))
                return (TransactionStatus)copiedObjects[this];
            copy = copy ?? new TransactionStatus();
            if (!asNew)
            {
                copy.TransientId = this.TransientId;
                copy.Id = this.Id;
            }
            copy.TransactionDateOccured = this.TransactionDateOccured;
            copy.Status = this.Status;
            copy.Shipped = this.Shipped;
            copy.Invoiced = this.Invoiced;
            copy.ShippedDateOccured = this.ShippedDateOccured;
            copy.InvoicedDateOccured = this.InvoicedDateOccured;
            copy.Cancelled = this.Cancelled;
            copy.InTransit = this.InTransit;
            copy.Picked = this.Picked;
            copy.PaymentStatus = this.PaymentStatus;
            copy.InitialOrderDate = this.InitialOrderDate;
            copy.FinalOrderDate = this.FinalOrderDate;
            copy.Delivered = this.Delivered;
            copy.Ordered = this.Ordered;
            if (!copiedObjects.Contains(this))
            {
                copiedObjects.Add(this, copy);
            }
            return copy;
        }

        public override bool Equals(object obj)
        {
            var compareTo = obj as TransactionStatus;
            if (ReferenceEquals(this, compareTo))
            {
                return true;
            }
            if (compareTo == null || !this.GetType().Equals(compareTo.GetTypeUnproxied()))
            {
                return false;
            }
            if (this.HasSameNonDefaultIdAs(compareTo))
            {
                return true;
            }
            // Since the Ids aren't the same, both of them must be transient to
            // compare domain signatures; because if one is transient and the
            // other is a persisted entity, then they cannot be the same object.
            return this.IsTransient() && compareTo.IsTransient() && (base.Equals(compareTo) || this.TransientId.Equals(compareTo.TransientId));
        }

// Maintain equality operator semantics for entities.
        public static bool operator ==(TransactionStatus x, TransactionStatus y)
        {
            // By default, == and Equals compares references. In order to
            // maintain these semantics with entities, we need to compare by
            // identity value. The Equals(x, y) override is used to guard
            // against null values; it then calls EntityEquals().
            return Equals(x, y);
        }

// Maintain inequality operator semantics for entities.
        public static bool operator !=(TransactionStatus x, TransactionStatus y)
        {
            return !(x == y);
        }

        private PropertyInfo __propertyKeyCache;
        public virtual PropertyInfo GetPrimaryKey()
        {
            if (__propertyKeyCache == null)
            {
                __propertyKeyCache = this.GetType().GetProperty("Id");
            }
            return __propertyKeyCache;
        }


/// <summary>
///     To help ensure hashcode uniqueness, a carefully selected random number multiplier
///     is used within the calculation.  Goodrich and Tamassia's Data Structures and
///     Algorithms in Java asserts that 31, 33, 37, 39 and 41 will produce the fewest number
///     of collissions.  See http://computinglife.wordpress.com/2008/11/20/why-do-hash-functions-use-prime-numbers/
///     for more information.
/// </summary>
        private const int HashMultiplier = 31;
        private int? cachedHashcode;

        public override int GetHashCode()
        {
            if (this.cachedHashcode.HasValue)
            {
                return this.cachedHashcode.Value;
            }
            if (this.IsTransient())
            {
                //this.cachedHashcode = base.GetHashCode();
                return this.TransientId.GetHashCode(); //don't cache because this won't stay transient forever
            }
            else
            {
                unchecked
                {
                    // It's possible for two objects to return the same hash code based on
                    // identically valued properties, even if they're of two different types,
                    // so we include the object's type in the hash calculation
                    var hashCode = this.GetType().GetHashCode();
                    this.cachedHashcode = (hashCode * HashMultiplier) ^ this.Id.GetHashCode();
                }
            }
            return this.cachedHashcode.Value;
        }

/// <summary>
///     Transient objects are not associated with an item already in storage.  For instance,
///     a Customer is transient if its Id is 0.  It's virtual to allow NHibernate-backed
///     objects to be lazily loaded.
/// </summary>
        public virtual bool IsTransient()
        {
            return this.Id == default(int) || this.Id.Equals(default(int));
        }

/// <summary>
///     When NHibernate proxies objects, it masks the type of the actual entity object.
///     This wrapper burrows into the proxied object to get its actual type.
///
///     Although this assumes NHibernate is being used, it doesn't require any NHibernate
///     related dependencies and has no bad side effects if NHibernate isn't being used.
///
///     Related discussion is at http://groups.google.com/group/sharp-architecture/browse_thread/thread/ddd05f9baede023a ...thanks Jay Oliver!
/// </summary>
        protected virtual System.Type GetTypeUnproxied()
        {
            return this.GetType();
        }

/// <summary>
///     Returns true if self and the provided entity have the same Id values
///     and the Ids are not of the default Id value
/// </summary>
        protected bool HasSameNonDefaultIdAs(TransactionStatus compareTo)
        {
            return !this.IsTransient() && !compareTo.IsTransient() && this.Id.Equals(compareTo.Id);
        }

        #endregion


    }
}
