
// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).

using System;
using System.Runtime.Serialization;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Collections;
using zAppDev.DotNet.Framework.Utilities;
using zAppDev.DotNet.Framework.Configuration;
using zAppDev.DotNet.Framework.Data.Domain;

using DemonstratorApp.DAL;

namespace DemonstratorApp.BO
{
	/// <summary>
	/// The MapPoint extensions
	/// </summary>
	public static class MapPointExtensions
	{
        public static System.Collections.Generic.List<DemonstratorApp.BO.MapPoint> InitiOrderMapPoints(DemonstratorApp.BO.Order order){using (new zAppDev.DotNet.Framework.Profiling.Profiler("MapPoint", zAppDev.DotNet.Framework.Profiling.AppDevSymbolType.ClassOperation, "InitiOrderMapPoints")) {
System.Collections.Generic.List<DemonstratorApp.BO.MapPoint> mapPoints = new System.Collections.Generic.List<DemonstratorApp.BO.MapPoint>();
DemonstratorApp.BO.MapPoint fromPoint = new DemonstratorApp.BO.MapPoint();
if ((((((order?.From ?? "") == null || (order?.From ?? "") == "")) == false))) {
}
fromPoint.Address = (order?.From ?? "");fromPoint.Title = "Shipping From";fromPoint.Icon = "http://apps.zappdev.com/TomeFinance_1242_vvasilopoulos/resources/images/" + "industries.png";mapPoints?.Add(fromPoint);
if (((order?.IntermediateParty ?? false))) {
foreach (var bol in order?.BillOfLandings ?? Enumerable.Empty<DemonstratorApp.BO.BillOfLanding>()) {
if ((bol?.LandingPlace == order?.From)) {
continue;}
DemonstratorApp.BO.MapPoint intermediaryFromPoint = new DemonstratorApp.BO.MapPoint();
if ((((((bol?.LandingPlace ?? "") == null || (bol?.LandingPlace ?? "") == "")) == false))) {
}
intermediaryFromPoint.Address = (bol?.LandingPlace ?? "");intermediaryFromPoint.Icon = "transport.png";intermediaryFromPoint.Title = "Intermediary Landing Place";mapPoints?.Add(intermediaryFromPoint);
if ((bol?.DeliveryPlace == order?.DeliveryTo)) {
continue;}
DemonstratorApp.BO.MapPoint intemediaryToPoint = new DemonstratorApp.BO.MapPoint();
if ((((((bol?.DeliveryPlace ?? "") == null || (bol?.DeliveryPlace ?? "") == "")) == false))) {
}
intemediaryToPoint.Address = (bol?.DeliveryPlace ?? "");intemediaryToPoint.Icon = "transport.png";intemediaryToPoint.Title = "Intermediary Delivery Place";mapPoints?.Add(intemediaryToPoint);
}
}
DemonstratorApp.BO.MapPoint deliveryPoint = new DemonstratorApp.BO.MapPoint();
if ((((((order?.DeliveryTo ?? "") == null || (order?.DeliveryTo ?? "") == "")) == false))) {
}
deliveryPoint.Address = (order?.DeliveryTo ?? "");deliveryPoint.Title = "Delivery To";deliveryPoint.Icon = "commercial-places.png";mapPoints?.Add(deliveryPoint);
return mapPoints;
}
}



        
	}
}
