
// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).

using System;
using System.Runtime.Serialization;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Collections;
using zAppDev.DotNet.Framework.Utilities;
using zAppDev.DotNet.Framework.Configuration;
using zAppDev.DotNet.Framework.Data.Domain;

using DemonstratorApp.DAL;

namespace DemonstratorApp.BO
{
	/// <summary>
	/// The ProofOfDelivery extensions
	/// </summary>
	public static class ProofOfDeliveryExtensions
	{
        public static System.Collections.Generic.List<DemonstratorApp.BO.ProofOfDelivery> FindAgreement(){using (new zAppDev.DotNet.Framework.Profiling.Profiler("ProofOfDelivery", zAppDev.DotNet.Framework.Profiling.AppDevSymbolType.ClassOperation, "FindAgreement")) {
string userName = "";
System.Collections.Generic.List<DemonstratorApp.BO.Agreement> agreements = new DemonstratorApp.DAL.Repository().Get<DemonstratorApp.BO.Agreement>((a) => a.Investor.UserName == zAppDev.DotNet.Framework.Identity.IdentityHelper.GetCurrentApplicationUser().UserName);
System.Collections.Generic.List<DemonstratorApp.BO.ProofOfDelivery> foundPODs = new System.Collections.Generic.List<DemonstratorApp.BO.ProofOfDelivery>();
foreach (var agr in agreements ?? Enumerable.Empty<DemonstratorApp.BO.Agreement>()) {
userName = (agr?.Supplier?.UserName ?? "");foreach (var pod in new DemonstratorApp.DAL.Repository().Get<DemonstratorApp.BO.ProofOfDelivery>((o) => o.Transaction.Supplier.UserName == userName) ?? Enumerable.Empty<DemonstratorApp.BO.ProofOfDelivery>()) {
foundPODs?.Add(pod);
zAppDev.DotNet.Framework.Utilities.DebugHelper.Log(zAppDev.DotNet.Framework.Utilities.DebugMessageType.Warning, "ProofOfDelivery",  DemonstratorApp.Hubs.EventsHub.RaiseDebugMessage, "length foundOrders: " + (foundPODs?.Count().ToString() ?? ""));
}
}
return foundPODs;
}
}



        
	}
}
