// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).

using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using FluentNHibernate.Testing;
using DemonstratorApp.BO;
using DemonstratorApp.BoTesting.Tests.Common;
using DemonstratorApp.DAL;

namespace DemonstratorApp.BoTesting.Tests
{
    /// <summary>
    ///This is a test class for FundedTransactionTest and is intended
    ///to contain all FundedTransactionTest NUnit Tests
    ///</summary>
    [TestFixture]
    [Description("FundedTransaction Repository Tests")]
    [Category("FundedTransaction Repository Tests")]
    internal class FundedTransactionTests : NHibernateFixture
    {
        /// <summary>
        ///A test for testing the persistence of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the persistence of `FundedTransaction`")]
        [Order(0)]
        public void FundedTransaction_persistence_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            new PersistenceSpecification<DemonstratorApp.BO.FundedTransaction>(Session)
            .CheckProperty(p => p.FundingPercentage, "FundedTransaction_FundingPercentage")
            .CheckProperty(p => p.TransactionStatus, "FundedTransaction_TransactionStatus")
            .VerifyTheMappings();
        }

        /// <summary>
        ///A test for testing the filtering of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the filtering of `FundedTransaction`")]
        [Order(1)]
        public void FundedTransaction_filtering_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            var repo = new Repository(Session);
            List<DemonstratorApp.BO.FundedTransaction> results = null;
            Assert.DoesNotThrow(() =>
            {
                results = repo.GetAsQueryable<DemonstratorApp.BO.FundedTransaction>(
                              a => true
                              && (a.FundingPercentage != string.Empty && a.FundingPercentage != null)
                              && (a.TransactionStatus != string.Empty && a.TransactionStatus != null)
                              ,
                              cacheQuery: true)
                          .OrderBy(a => a)
                          .Skip(0)
                          .Take(3)
                          .ToList();
            });
            Assert.AreNotEqual(null, results);
        }
    }
}