// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).

using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using FluentNHibernate.Testing;
using DemonstratorApp.BO;
using DemonstratorApp.BoTesting.Tests.Common;
using DemonstratorApp.DAL;

namespace DemonstratorApp.BoTesting.Tests
{
    /// <summary>
    ///This is a test class for SupplierStatisticTest and is intended
    ///to contain all SupplierStatisticTest NUnit Tests
    ///</summary>
    [TestFixture]
    [Description("SupplierStatistic Repository Tests")]
    [Category("SupplierStatistic Repository Tests")]
    internal class SupplierStatisticTests : NHibernateFixture
    {
        /// <summary>
        ///A test for testing the persistence of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the persistence of `SupplierStatistic`")]
        [Order(0)]
        public void SupplierStatistic_persistence_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            var _dashboard_supplier_supplierstatistics = new DemonstratorApp.BO.Supplier
            {
                SupplierId = 6749,
                Company = "Supplier_Company",
                CompanyLogo = "Supplier_CompanyLogo",
                Business = "Supplier_Business",
                CurrentAmount = "Supplier_CurrentAmount",
                AverageAmount = "Supplier_AverageAmount",
                PercentageOfCreditNotes = "Supplier_PercentageOfCreditNotes",
                PrimaryPhone = "Supplier_PrimaryPhone",
                SecondaryPhone = "Supplier_SecondaryPhone",
                Fax = "Supplier_Fax",
                WebSite = "Supplier_WebSite",
                AcceptedPolicyTerms = true,
                SupplierStatus = "Supplier_SupplierStatus",
                DomainFocus = "Supplier_DomainFocus",
                EvaluationResult = "Supplier_EvaluationResult",
                EvaluationCountResult = 3990,
                AnnualTurnover = true,
                BEnvironment = true,
                PTerms = true,
                Average = true,
                InvoiceValue = true,
                EqRatio = true,
                Prefix = "Supplier_Prefix",
                VATNumber = "Supplier_VATNumber",
                MarketSegment = "Supplier_MarketSegment",
                AdditionalComments = "Supplier_AdditionalComments",
                AdditionalCommentsStep2 = "Supplier_AdditionalCommentsStep2",
                AdditionalCommentsStep3 = "Supplier_AdditionalCommentsStep3",
                UserName = "db56f069-1570-4f1b-939c-46f7a0f75609Supplier_UserName",
                PasswordHash = "Supplier_PasswordHash",
                SecurityStamp = "Supplier_SecurityStamp",
                EmailConfirmed = true,
                LockoutEnabled = true,
                PhoneNumberConfirmed = true,
                TwoFactorEnabled = true,
                AccessFailedCount = 6791,
                Name = "Supplier_Name",
                Email = "Supplier_Email",
                PhoneNumber = "Supplier_PhoneNumber",
                LockoutEndDate = now,
            };
            new PersistenceSpecification<DemonstratorApp.BO.SupplierStatistic>(Session)
            .CheckProperty(p => p.TotalCommercialAgreements, 1565)
            .CheckProperty(p => p.DataQuality, 222222.22M)
            .CheckProperty(p => p.DataAvailability, 8769)
            .CheckProperty(p => p.OnTimeDeliveries, 567)
            .CheckProperty(p => p.AsOrderedDeliveries, 6842)
            .CheckProperty(p => p.InFullDeliveries, 3360)
            .CheckProperty(p => p.TotalImpeachments, 1418)
            .CheckProperty(p => p.CurrentTurnover, 222222.22M)
            .CheckProperty(p => p.NextTurnover, 222222.22M)
            .CheckProperty(p => p.PreviousTurnover, 222222.22M)
            .CheckProperty(p => p.TotalTransactions, 599)
            .CheckReference(p => p.Supplier, _dashboard_supplier_supplierstatistics)
            .VerifyTheMappings();
        }

        /// <summary>
        ///A test for testing the filtering of an object from Db
        ///</summary>
        [Test]
        [Description("This tests the filtering of `SupplierStatistic`")]
        [Order(1)]
        public void SupplierStatistic_filtering_test()
        {
            DateTime now = DateTime.Now;
            // Get datetime without milliseconds
            now = new DateTime(now.Ticks - (now.Ticks % TimeSpan.TicksPerSecond), now.Kind);
            var repo = new Repository(Session);
            List<DemonstratorApp.BO.SupplierStatistic> results = null;
            Assert.DoesNotThrow(() =>
            {
                results = repo.GetAsQueryable<DemonstratorApp.BO.SupplierStatistic>(
                              a => true
                              && (a.TotalCommercialAgreements + 123 > 0)
                              && (a.DataQuality + 123 > 0)
                              && (a.DataAvailability + 123 > 0)
                              && (a.OnTimeDeliveries + 123 > 0)
                              && (a.AsOrderedDeliveries + 123 > 0)
                              && (a.InFullDeliveries + 123 > 0)
                              && (a.TotalImpeachments + 123 > 0)
                              && (a.CurrentTurnover + 123 > 0)
                              && (a.NextTurnover + 123 > 0)
                              && (a.PreviousTurnover + 123 > 0)
                              && (a.TotalTransactions + 123 > 0)
                              && a.Supplier != null
                              ,
                              cacheQuery: true)
                          .OrderBy(a => a)
                          .Skip(0)
                          .Take(3)
                          .ToList();
            });
            Assert.AreNotEqual(null, results);
        }
    }
}