// Copyright (c) CLMS. All rights reserved.
// Licensed under the AGPL-3.0 license. See LICENSE file in the project root for full license information.
// This source file was autogenerated by zAppDev(r).
using System;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using DemonstratorApp.BO;
using DemonstratorApp.UI.Controllers.SignInPage;
using AppCode;
using zAppDev.DotNet.Framework.Data;
using zAppDev.DotNet.Framework.Utilities;
using zAppDev.DotNet.Framework.Data.Domain;
using zAppDev.DotNet.Framework.Mvc;
using System.ComponentModel.DataAnnotations;
using DemonstratorApp.UI.ViewModels.MasterPageSignIn;
using DemonstratorApp.UI.Controllers.MasterPageSignIn;
namespace DemonstratorApp.UI.ViewModels.SignInPage
{
    public class SignInPageViewModel : MasterPageSignInViewModel
    {
        public string PasswordTextBox;
        public string UserNameTextBox;
        public bool RememberMeCB;


        public SignInPageViewModel()
        {
        }


        public override void Evict()
        {
            var manager = MiniSessionManager.Instance;
        }

    }


    [OriginalType(typeof(DemonstratorApp.UI.ViewModels.SignInPage.SignInPageViewModel))]
    public class SignInPageViewModelDTO : MasterPageSignInViewModelDTO, IViewModelDTO<DemonstratorApp.UI.ViewModels.SignInPage.SignInPageViewModel>
    {

        [JsonConstructor]
        public SignInPageViewModelDTO() { }
        public SignInPageViewModelDTO(DemonstratorApp.UI.ViewModels.SignInPage.SignInPageViewModel original, bool parentIsDirty = false)  : base(original)
        {
            if (original == null) return;
            _runtimeType = original.GetType().FullName;
            PasswordTextBox = original.PasswordTextBox;
            UserNameTextBox = original.UserNameTextBox;
            RememberMeCB = original.RememberMeCB;
        }
        public string PasswordTextBox;
        public string UserNameTextBox;
        public bool RememberMeCB;
        public new string _runtimeType
        {
            get;
            set;
        }
        public override string _originalTypeClassName => typeof(DemonstratorApp.UI.ViewModels.SignInPage.SignInPageViewModel).FullName;

        public new DemonstratorApp.UI.ViewModels.SignInPage.SignInPageViewModel GetModel()
        {
            var alreadySeenInstance = DTOHelper.GetSeenModelInstance<DemonstratorApp.UI.ViewModels.SignInPage.SignInPageViewModel>(_clientKey, _originalTypeClassName, _baseClasses);
            if (alreadySeenInstance != null) return alreadySeenInstance;
            return new DemonstratorApp.UI.ViewModels.SignInPage.SignInPageViewModel();
        }
        new  public DemonstratorApp.UI.ViewModels.SignInPage.SignInPageViewModel Convert()
        {
            var original = GetModel();
            if (original == null)
            {
                original = new DemonstratorApp.UI.ViewModels.SignInPage.SignInPageViewModel();
            }
            DTOHelper.UpdateSeenModelInstances(this, original);
            Hydrate(original);
            return original;
        }
        public void Hydrate(DemonstratorApp.UI.ViewModels.SignInPage.SignInPageViewModel original)
        {
            if (original == null) return;
            base.Hydrate(original);
            original.PasswordTextBox = PasswordTextBox;
            original.UserNameTextBox = UserNameTextBox;
            original.RememberMeCB = RememberMeCB;
        }
    }



}
